'''выносит изображения, на которых ошиблась recall с помощью сгенерированного файла.'''
import os
import argparse
import shutil

def get_arguments():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--data_file",
        required=True,
        help="Data file generated by 'recall.py'"
    )
    ap.add_argument(
        "--save_path",
        required=True,
        help="Path to save dumped images"
    )
    return vars(ap.parse_args())

def main():
    args = get_arguments()
    with open(args['data_file'], 'r') as f:
        data = f.readlines()
    for line in data:
        if ('-----' in line):
            data.remove(line)

    for line in data:
        if ('Target' in line):
            data.remove(line)

    for path in data:
        shutil.move(path[:-1], args['save_path'])
    print(len(data))

if __name__ == '__main__':
    main()
